[[xfail]]
test = "scenario/triggers/val_time_to_collision_start_trigger.py::*"
reason = "TTC not supported by Tool v0.0.1"

[[xfail]]
test = "scenario/sequencing/val_split_*.py::*"
reason = "Sequencing not implemented by Tool v0.0.1"

[[xfail]]
test = "scenario/trajectories/val_interpolation.py::test_timed_polyline_trajectory_interpolation"
except = ["linear_position-*"]
reason = "Only linear position interpolation variants are expected to pass for this tool"
