[pytest]
testpaths = scenario
python_files = val_*.py
filterwarnings = ignore::DeprecationWarning
markers =
    validation_feature(name): OpenSCENARIO feature covered by the validation case
    validation_category(name): Validation case category
